CREATE DATABASE IF NOT EXISTS aldaron_db;

USE aldaron_db;

CREATE TABLE PAGOS (
IDPAGO VARCHAR(200) NOT NULL,
IDINSCRITO VARCHAR(200),
IMPORTE DOUBLE NOT NULL,
COMPLETO INT NOT NULL,
OBSERVACIONES LONGTEXT,
FECHA LONG NOT NULL,
FECHA_UPDATE LONG NOT NULL,
ESTADO INT NOT NULL
);
CREATE TABLE INSCRIPCIONESACTIVIDADES (
    IDACTIVIDAD VARCHAR(200) NOT NULL,
    IDINSCRITO VARCHAR(200) NOT NULL,
    OBSERVACIONES LONGTEXT,
    FECHA LONG,
    FECHA_UPDATE LONG,
    ESTADO INT
);
CREATE TABLE HABITACIONES (
    IDHABITACION VARCHAR(200) NOT NULL,
    IDENTIFICADOR VARCHAR(200),
    PLAZAS INT NOT NULL,
    CAMAS INT NOT NULL,
    OBSERVACIONES LONGTEXT,
    FECHA TIMESTAMP,
    HORA_BLOQUEO LONG,
    ESTADO INT NOT NULL,
    PLANTA VARCHAR(100) NOT NULL,
    ALEATORIA INT NOT NULL,
    OCUPACION INT,
    PRECIO_ADULTO DOUBLE,
    PRECIO_MENOR DOUBLE
);

CREATE TABLE HABITACIONESPARCIALES (
    IDHABITACION VARCHAR(200) NOT NULL,
    IDHABITACIONRAIZ VARCHAR(200) NOT NULL,
    FECHA LONG,
    HORA_BLOQUEO LONG,
    ESTADO INT NOT NULL
);

CREATE TABLE NOTICIAS (
    IDNOTICIA VARCHAR(200) NOT NULL,
    TITULO VARCHAR(400) NOT NULL,
    CUERPO LONGTEXT NOT NULL,
    FECHA LONG,
    FECHAUPDATE LONG,
    ESTADO INT NOT NULL
);

CREATE TABLE INSCRITOS (
    IDINSCRITO VARCHAR(200) NOT NULL,
    NOMBRE VARCHAR(400) NOT NULL,
    APELLIDOS VARCHAR(400) NOT NULL,
    PSEUDONIMO VARCHAR(400),
    SMIAL VARCHAR(400),
    NIF VARCHAR(100),
    EMAIL VARCHAR(400),
    TELEFONO VARCHAR(100),
    TELEGRAM VARCHAR(200),
    MENOR VARCHAR(12),
    ALERGIAS INT ,
    ALERGIAS_TXT VARCHAR(400),
    ALIMENTOS INT ,
    CON_BEBES INT,
    LOPD INT,
    ALIMENTOS_TXT VARCHAR(400),
    OBSERVACIONES LONGTEXT,
    FECHA LONG,
    FECHAUPDATE LONG,
    HABITACION VARCHAR(400),
    ESTADO INT NOT NULL
);

CREATE TABLE USUARIOS (

ID VARCHAR(200) NOT NULL,
IDINSCRITO VARCHAR(200) NOT NULL,
USUARIO VARCHAR(100) NOT NULL,
PASSWORD VARCHAR(200) NOT NULL,
IDSESION VARCHAR(200),
FECHA_SESION LONG,
FECHA LONG,
FECHA_UPDATE LONG);

CREATE TABLE ESPACIOS (
    IDESPACIO VARCHAR(200) NOT NULL,
    NOMBRE VARCHAR(200),
    AFORO INT NOT NULL,
    DESCRIPCION LONGTEXT,
    FECHA LONG,
    FECHA_UPDATE LONG,
    ESTADO INT NOT NULL,
    PLANTA VARCHAR(100) NOT NULL
);

CREATE TABLE PLANIFICACION (
    IDPLANIFICACION VARCHAR(200) NOT NULL,
    FECHA VARCHAR(200),
    ESPACIO VARCHAR(1000),
    INTERVALO INT,
    ACTIVIDAD VARCHAR(200),
    NOMBRE_ACTIVIDAD VARCHAR(500),
    COLOR VARCHAR(100),
    FECHA_CREACION LONG,
    FECHA_UPDATE LONG
);


CREATE TABLE ACTIVIDAD (
    IDACTIVIDAD VARCHAR(200) NOT NULL,
    NOMBRE VARCHAR(200),
    RESPONSABLES_ID VARCHAR(400),
    RESPONSABLES_PSEUDONIMOS VARCHAR(400),
    DESCRIPCION LONGTEXT,
    AFORO INT NOT NULL,
    FECHA_ACTIVIDAD LONG,
    HORA_INICIO LONG,
    HORA_FIN LONG,
    FECHA_CREACION LONG,
    FECHA_UPDATE LONG,
    ESTADO INT NOT NULL,
    PUBLICO VARCHAR(100) NOT NULL,
    PAGO_ADICIONAL INT,
    DURACION VARCHAR(100)
);

CREATE USER 'estelcon' identified by 'M3r3th4d3rth4d';
CREATE USER 'estelcon@localhost' identified by 'M3r3th4d3rth4d';
GRANT ALL PRIVILEGES ON aldaron_db.* TO 'estelcon';
GRANT ALL PRIVILEGES ON aldaron_db.* TO 'estelcon@localhost';
FLUSH PRIVILEGES;

