version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Usar el Dockerfile del servicio principal
    container_name: estelcon-app
    # Vincular archivos de configuración desde el host
    volumes:
      - ./files/default.config.nginx:/etc/nginx/sites-available/default
      - ./files/vsftpd.conf:/etc/vsftpd.conf
      - ./files/vsftpd.sh:/etc/init.d/vsftpd.sh
      - ./files/vsftpd_virtual:/etc/vsftpd_virtual
      - ./files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
      - ./files/init-mariadb.sql:/var/www/init-mariadb.sql
      - ./files/mysql-connector-j-8.0.32.jar:/usr/local/tomcat/lib/mysql-connector-j-8.0.32.jar
      - ./files/start-services.sh:/usr/local/bin/start-services.sh
      - ./files/50-server.cnf:/var/www/50-server.cnf
      - ./files/mariadb.sh:/etc/init.d/mariadb.sh
      - ./files/estelcon.properties:/home/estelcon/estelcon.properties
      - ./wars:/usr/local/tomcat/webapps # Persistencia de los archivos WAR
    # Variables de entorno opcionales
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      FTP_USER: ftpestelcon
      FTP_PASSWORD: P4ssw0rd
    # Exponer los puertos
    ports:
      - "8085:8080"
      - "86:80"
      - "8445:8443"
      - "2121:2121"
      - "2122:2122"
      - "22:22"
      - "40000:40000"
      - "3306:3306"
    networks:
      - estelcon-net

  db:
    image: mariadb:10.5
    container_name: estelcon-db
    # Configuración de base de datos
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    # Inicializar la base de datos con un script SQL
    volumes:
      - ./files/init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/mysql # Persistencia de los datos de la base de datos
    ports:
      - "3307:3306" # Puerto para acceso externo a la base de datos
    networks:
      - estelcon-net

networks:
  estelcon-net:
    driver: bridge

volumes:
  db_data: # Volumen para persistir los datos de la base de datos
