services:
  app:
    build:
      context: "./"
      dockerfile: "./Dockerfile"  # Usa el Dockerfile en el mismo directorio
    container_name: estelcon-app
    volumes:
      - "./files/default.config.nginx:/etc/nginx/sites-available/default"
      - "./files/vsftpd.conf:/etc/vsftpd.conf"
      - "./files/vsftpd.sh:/etc/init.d/vsftpd.sh"
      - "./files/vsftpd_virtual:/etc/vsftpd_virtual"
      - "./files/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
      - "./files/init-mariadb.sql:/var/www/init-mariadb.sql"
      - "./files/mysql-connector-j-8.0.32.jar:/usr/local/tomcat/lib/mysql-connector-j-8.0.32.jar"
      - "./files/start-services.sh:/usr/local/bin/start-services.sh"
      - "./files/50-server.cnf:/var/www/50-server.cnf"
      - "./files/mariadb.sh:/etc/init.d/mariadb.sh"
      - "./files/estelcon.properties:/home/estelcon/estelcon.properties"
      - "./wars:/usr/local/tomcat/webapps"
      - "./tomcat_logs:/usr/local/tomcat/logs"
      - "./local_activity:/home/estelcon/activity"
      - "./local_error:/home/estelcon/error"
      - "./local_log:/home/estelcon/log"
      - "./local_outbox:/home/estelcon/outbox"
      - "./local_plantillas:/home/estelcon/plantillas"
      - "./local_sent:/home/estelcon/sent"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      FTP_USER: ftpestelcon
      FTP_PASSWORD: P4ssw0rd
    ports:
      - "8080:8080"
      - "86:80"
      - "8445:8443"
      - "2121:2121"
      - "2122:2122"
      - "22:22"
      - "40000:40000"
      - "3306:3306"
      - "9222:9222"
    networks:
      - dockerdesarrollov2_estelcon-net

  db:
    image: mariadb:10.5
    container_name: estelcon-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - "./db_data:/var/lib/mysql"
      - "./files/init-mariadb.sql:/docker-entrypoint-initdb.d/init.sql"
    networks:
      - dockerdesarrollov2_estelcon-net
    ports:
      - "3307:3306"

networks:
  dockerdesarrollov2_estelcon-net:
    driver: bridge